### ISSUE TITLE
Protocol iv monocompartment urine failed

### ISSUE THREAD

**Issue by vabrishami** [cossorzano/scipion#2]
I tried to run test for example 5 and this protocol failed with this error:

00038:       optimizer1.optimize()
00039:     File "/home/vahid/xcipion/pyworkflow/em/data.py", line 1197, in optimize
00040:       self.printFitting()
00041:     File "/home/vahid/xcipion/pyworkflow/em/data.py", line 1171, in printFitting
00042:       self._printFitting(self.model.x, self.model.y, yPredicted)
00043:     File "/home/vahid/xcipion/pyworkflow/em/data.py", line 1136, in _printFitting
00044:       if y.size==0:
00045:   AttributeError: 'list' object has no attribute 'size'
00046:   Protocol failed: 'list' object has no attribute 'size'

I pushed this example to the repository. Could you please have a look.

**Comment by cossorzano** [comment]
Try now

**Comment by vabrishami** [comment]
It works fine. Thanks!
