### ISSUE TITLE
ProtPKPDIVTwoCompartments fails

### ISSUE THREAD

**Issue by vabrishami** [cossorzano/scipion#3]
When I tried to execute example 7 this protocol failed with this error:

00071:   Exception: Error in the local optimizer
00072:   The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Errors in the local optimizer may be caused by starting from a bad initial guess
00073:   Try performing a global search first or changing the bounding box
00074:   Protocol failed: Error in the local optimizer
00075:   The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Errors in the local optimizer may be caused by starting from a bad initial guess
00076:   Try performing a global search first or changing the bounding box
00077:   FAILED: runFit, step 1

Could you please have a look.

**Comment by cossorzano** [comment]
I'll check it, thank you Vahid.

**Comment by cossorzano** [comment]
The problem was with printing. Solved.
